
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SignetSSRProject.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
public partial class Attendance
{

    public int AttendanceID { get; set; }

    [Required]
    public int EmployeeID { get; set; }

    [Required]
    [DataType(DataType.Date)]
    [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
    public System.DateTime Date { get; set; }

     [Required]
    public string Attendance1 { get; set; }

     [Required]
    public Nullable<decimal> HoursMissed { get; set; }

    [Required]
    public string Reason { get; set; }

    [UIHint("TrueFalse")]
    public Nullable<bool> Excused { get; set; }

    
    public Nullable<decimal> CostOption { get; set; }



    public virtual Employee Employee { get; set; }

}

}
