
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SignetSSRProject.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
public partial class Customer
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Customer()
    {

        this.Jobs = new HashSet<Job>();

    }


    public int CustomerID { get; set; }

    [Required]
    public string FirstName { get; set; }

    [Required]
    public string LastName { get; set; }

    [Required]
    public string Company { get; set; }

    [Required]
    public string Title { get; set; }

    [Required]
    [DataType(DataType.PhoneNumber)]
    public string BusinessPhone { get; set; }

    [Required]
    [DataType(DataType.PhoneNumber)]
    public string HomePhone { get; set; }

    [Required]
    [DataType(DataType.PhoneNumber)]
    public string CellPhone { get; set; }

    [DataType(DataType.PhoneNumber)]
    public string FaxNumber { get; set; }

    [Required]
    [DataType(DataType.EmailAddress)]
    public string EmailAddress { get; set; }

    public string Notes { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Job> Jobs { get; set; }

}

}
