
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SignetSSRProject.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
public partial class Employee
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Employee()
    {

        this.Attendances = new HashSet<Attendance>();

        this.HoursWorkeds = new HashSet<HoursWorked>();

        this.WageHistories = new HashSet<WageHistory>();

    }


    public int EmployeeID { get; set; }

    [Required]
    public string FirstName { get; set; }

    [Required]
    public string LastName { get; set; }

    [Required]
    public string JobTitle { get; set; }

    [UIHint ("TrueFalse")]
    public Nullable<bool> Supervisor { get; set; }

    [UIHint("TrueFalse")]
    public Nullable<bool> ContractLabor { get; set; }

    [Required]
    [DataType(DataType.Currency)]
    public Nullable<decimal> WageRateRT { get; set; }

    [Required]
    [DataType(DataType.Currency)]
    public Nullable<decimal> WageRateOT { get; set; }

    [Required]
    [DataType(DataType.PhoneNumber)]
    public string HomePhone { get; set; }

    [Required]
    [DataType(DataType.PhoneNumber)]
    public string CellPhone { get; set; }
   
    [Required]
    public string Address { get; set; }

    [Required]
    [DataType(DataType.EmailAddress)]
    public string EmailAddress { get; set; }

    public string Notes { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Attendance> Attendances { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HoursWorked> HoursWorkeds { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<WageHistory> WageHistories { get; set; }

}

}
