
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SignetSSRProject.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
public partial class HoursWorked
{

    public int HoursWorkedID { get; set; }

    [Required]
    public int EmployeeID { get; set; }
    
    [Required]
    public int JobID { get; set; }

     [Required]
    [DataType(DataType.Date)]
    [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
    public System.DateTime Date { get; set; }

     [Required]
     [DataType(DataType.Currency)]
    public Nullable<decimal> HoursWorkedRT { get; set; }
   
    [Required]
    [DataType(DataType.Currency)]
    public Nullable<decimal> HoursWorkedOT { get; set; }
   
    [Required]
    public Nullable<int> ItemNumber { get; set; }
    
    [Required]
    public Nullable<int> WageHistoryID { get; set; }

     [Required]
    public string JobDescription { get; set; }



    public virtual Employee Employee { get; set; }

    public virtual Job Job { get; set; }

    public virtual WageHistory WageHistory { get; set; }

}

}
