
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SignetSSRProject.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
public partial class MaterialsExpense
{

    public int MaterialsExpenseID { get; set; }

    [Required]
    public decimal Expense { get; set; }
     [Required]
    public int JobID { get; set; }
     [Required]
    public string ExpenseDescription { get; set; }
     [Required]
    public string PONumber { get; set; }
     [Required]
    public string InvoiceNumber { get; set; }

    public Nullable<bool> TaxIncluded { get; set; }

    public Nullable<decimal> TaxPercentage { get; set; }

    public Nullable<decimal> MarkupPercentage { get; set; }

    public Nullable<int> ItemNumber { get; set; }

    public Nullable<System.DateTime> ExpenseDate { get; set; }

    public Nullable<bool> InvoiceReceived { get; set; }



    public virtual Job Job { get; set; }

}

}
