//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignetSSRProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class WageHistory
    {
        [Required]
        public int WageHistoryID { get; set; }
        [Required]
        public int EmployeeID { get; set; }
        [Required]
        public int WageRT { get; set; }
        [Required]
        public int WageOT { get; set; }
        [Required]
        public Nullable<System.DateTime> DateStart { get; set; }
        [Required]
        public Nullable<System.DateTime> DateEnd { get; set; }
        [Required]
        public bool IsCurrent { get; set; }

        [Required]
        public virtual Employee Employee { get; set; }
    }
}
